WebMVCApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMVCApplication.Context;

namespace WebMVCApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        MVCWebHiFiApplicationDatabaseEntities db = new MVCWebHiFiApplicationDatabaseEntities();

        //[Authorize]
        public ActionResult Index()
        {
            return View(/*db.Users.ToList()*/);
        }

       /* public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }*/
    }
}

WebMVCApplication/Controllers/TextEditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebMVCApplication.BL;
using WebMVCApplication.Models;
using WebMVCApplication.Context;

namespace WebMVCApplication.Controllers
{
    [Authorize]    
    public class TextEditorController : Controller
    {
        // GET: TextEditor
        public ActionResult Index()
        {           
            return View();
        }             

        TextEditorBL textEditorBL = new TextEditorBL();       

        //Save Data Text        
        [HttpPost]
        public JsonResult Save(TextEditor textEditor)
        {
            try
            {
                textEditor = textEditorBL.Save(textEditor);
            }
            catch (Exception ex)
            {
                textEditor = new TextEditor();
                textEditor.Message = ex.Message;
            }
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string json = serializer.Serialize(textEditor);
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        //Get Data Text        
        [HttpPost]
        public JsonResult Get(TextEditor textEditor)
        {
            try
            {
                textEditor = textEditorBL.Get();
            }
            catch (Exception ex)
            {
                textEditor = new TextEditor();
                textEditor.Message = ex.Message;
            }
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string json = serializer.Serialize(textEditor);
            return Json(json, JsonRequestBehavior.AllowGet);
        }        

        MVCWebHiFiApplicationDatabaseEntities db = new MVCWebHiFiApplicationDatabaseEntities();
        //List All Text Data
        [AllowAnonymous]
        public ActionResult ViewAllText()
        {
            return View(db.TextEditors.ToList().OrderByDescending(x => x.EditorID));
        }

        //List All Text Data for Administration
        //View, Edit, and Delite text
        [Authorize (Roles = "Admin")]
        public ActionResult ViewAllTextAdministration()
        {
            return View(db.TextEditors.ToList().OrderByDescending(x => x.EditorID));
        }

        //View Last Text Data
        //View text and check to errors
        public ActionResult ViewLastText()
        {
            TextEditor textEditor;
            try
            {
                textEditor = textEditorBL.Get();
            }
            catch (Exception ex)
            {
                textEditor = new TextEditor();
                textEditor.Message = ex.Message;
            }             
            return View(textEditor);            
        }
    
        //View Just One Text Review
        public ActionResult ViewTextReview(int id = 0)
        {            
            return View(db.TextEditors.Find(id));
        }

        //Edit Text
        //Check Text for Error
        [Authorize(Roles = "Admin")]
        [ValidateInput(false)]
        public ActionResult EditText(int id)
        {
            TextEditor textEditor = db.TextEditors.Find(id);            
            if (textEditor == null)
            {
                return HttpNotFound();
            }
            return View(textEditor);
        }

        //Save Edit Text
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditText(TextEditor textEditor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(textEditor).State = System.Data.Entity.EntityState.Modified;                        
                db.SaveChanges();
                return RedirectToAction("ViewAllTextAdministration");
            }
            return View(textEditor);
        }

        //Find Id for Delete     
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            TextEditor textEditor = db.TextEditors.Find(id);
            if (textEditor == null)
            {
                return HttpNotFound();
            }
            return View(textEditor);
        }

        //Save state after Delete
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDeleteReview(int id = 0)
        {
            TextEditor textEditor = db.TextEditors.Find(id);
            db.TextEditors.Remove(textEditor);
            db.SaveChanges();
            return RedirectToAction("ViewAllTextAdministration");
        }
    }
}

WebMVCApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebMVCApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebMVCApplication/Views/Home/Index.cshtml
@model WebMVCApplication.Models.TextEditor

<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*if (User.Identity.IsAuthenticated)
                {*@
                    @Html.ActionLink("HiFi Audio", "ViewAllText", "TextEditor", new { area = "" }, new { @class = "navbar-brand" })
                @*}
                else
                {
                    <li>@Html.ActionLink("Login", "Login", "User")</li>
                }*@

            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-collapse navbar-right">
                    <li>@Html.ActionLink("Administration", "Index", "Home")</li>
                    <li>@Html.ActionLink("All Administration Text Review", "ViewAllTextAdministration", "TextEditor")</li>
                    <li>@Html.ActionLink("Login", "Login", "User")</li>
                    <li>@Html.ActionLink("Register Now", "Registration", "User")</li>
                    <li>@Html.ActionLink("View Text", "ViewLastText", "TextEditor")</li>
                    <li>@Html.ActionLink("List All User", "ListAllUser", "User")</li>                    
                </ul>
            </div>
        </div>
    </div>
</body>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Welcome @HttpContext.Current.User.Identity.Name
<br />

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Logout", "User", FormMethod.Post, new { id = "logoutForm" }))
    {
        <a href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
    }
}

<html>
<head>
    <meta charset="utf-8" />
    <link href="~/TextEditorContents/jquery-te-1.4.0.css" rel="stylesheet" />
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js" charset="utf-8"></script>
    <script src="~/TextEditorContents/jquery-te-1.4.0.min.js"></script>
</head>
<body>
    <form id="frm_details" method="post" name="frm_details">
        <br />
        <select class="form-control" id="dropDownList" name="DropDown">
            <option value="1" selected="true">Select Device</option>
            <option value="2">Amplifier</option>
            <option value="3">Turntable</option>
            <option value="4">Cartridge Turntable</option>
            <option value="5">Loudspeakers</option>
        </select>
        <br />
        Title:
        <br />
        <input id="Title" name="Title" placeholder="Your Title" type="text" />
        <br />
        <br />
        Review:
        <textarea id="txtArea" name="textarea"></textarea>
        Date Text:
        <br />
        <input id="dateCreate" type="date" name="DateText">
        <button id="btnSave" type="submit">Save</button>        
        <!-- <textarea id="txtArea1" style="width:100px; height:20px"></textarea><br />
    <button id="btnGet">Get</button>-->
    </form>
</body>
</html>
<body>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#txtArea").jqte();
        });
        
        $("#btnSave").click(function () {
            var textEditor = {
                Text: $("#txtArea").val(),
                Title: $('input[name=Title]').val(),
                CategoryID: $(document.getElementById('dropDownList')).val(),
                DateCreate: $('input[name=DateText]').val()
            };

            $.ajax({
                type: "POST",
                dataType: "json",
                url: "/TextEditor/Save",
                traditional: true,
                data: JSON.stringify(textEditor),
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    var textEditor1 = jQuery.parseJSON(data);
                    if ($.trim(textEditor1.Message) != "") {
                        alert(textEditor1.Message);
                        return false;
                    }
                    alert("Saved.");
                },
                error: function (xhr, status, error) {
                    alert(error);
                }
            });
        });

        $("#btnGet").click(function () {
            var textEditor = {};

            $.ajax({
                type: "POST",
                dataType: "json",
                url: "/TextEditor/Get",
                traditional: true,
                data: JSON.stringify(textEditor),
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    var textEditor1 = jQuery.parseJSON(data);
                    if ($.trim(textEditor1.Message) != "") {
                        alert(textEditor1.Message);
                        return false;
                    }
                    $("#txtArea1").val(textEditor1.Text);
                },
                error: function (xhr, status, error) {
                    alert(error);
                }
            });
        });
    </script>
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}